### ISSUE TITLE
[Feat] Criar uma conta

### ISSUE THREAD

**Issue by gabrielrom** [gabrielrom/ourbank-app#1]
## Descrição 
Como usuário do sistema, quero poder criar uma conta, para conseguir entrar na conta e ter acesso aos demais serviços.

## Critérios de aceitação 

* Ao clicar no botão de criar conta, deve ser verificado se o e-mail passado existe:

   * Caso e-mail passado ja existe, tera que ser mostrado um erro falando para o usuário que já existe um e-mail cadastrado.
   * Se não existir um e-mail cadastrado o usuário poderá criar uma conta e logo depois será redirecionado para a tela de login.

## Tasks

- [ ]  Criar a tela de signup utilizando os padrões do MVVM-C
- [ ]  Conectar com o backend
- [ ]  Tratar os errors e mostrar para o usuário se for necessário 
- [ ]  Fazer a navegação para a tela de login, caso a criação da conta retornar sucesso
